adding version support - also failing/exiting on retrieval failure
turnerlabs/sm_entrypoint pull request #6
Opened 2018-12-06 18:53 UTC by jhodnett2

This adds the ability to get secretmanager versions... 
This is how to add a secret with a version:`aws secretsmanager put-secret-value --secret-id test-env-poc-secrets --secret-string file://test.json --version-stages mytestversion.1`

Interesting gotcha with secerts versions: If you try to add a version label that already exists, it will move the version label to the new version....

2018-12-06 18:55 UTC, jhodnett2 commented
I forgot to mention, I also changed the functionality to FAIL if a secret can't be retrieved (or any other error that might occur)

So it should cause the container to stop instead of continuing with bad data.

2018-12-11 19:17 UTC, jritsema approved these changes

2018-12-11 19:42 UTC, mjreed-turner commented on README.md
> +  SM_VARS=secret-name-1[:version1],[secret-name-2[:AWSCURRENT],....]
That seems like an odd place to put the fact that the default version is `AWSCURRENT`...

2018-12-11 19:46 UTC, mjreed-turner commented on loadSecrets.go
> +      log.Fatalf("secretsmanager:GetSecretValue failed. (name: %s)\n %v", name, err)
Should include the version in the log message..

2018-12-11 19:46 UTC, mjreed-turner commented on loadSecrets.go
> +      log.Fatalf("secretsmanager:GetSecretValue returns invalid json. (name: %s)\n %v", name, err)
Here, too.

2018-12-11 20:10 UTC, mjreed-wbd requested changes

2018-12-11 20:10 UTC, mjreed-turner commented on README.md
> +  SM_VARS=secret-name-1[:version1],[secret-name-2[:AWSCURRENT],....]
change `[:AWSCURRENT]` to `[:version2]`.

2018-12-11 20:10 UTC, mjreed-turner commented on loadSecrets.go
> +    log.Printf("This SM_VAR is %s\nGetting Variable (name: %s) version %s", temp, name, version)
version should probably go inside parentheses, too. `(name: %s, version: %s)
`

2018-12-11 20:33 UTC, mjreed-wbd approved these changes

2018-12-11 20:50 UTC, merged